# Generated by Django 3.2.6 on 2021-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_pics/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('hashtags', models.TextField()),
            ],
        ),
    ]
